from __future__ import annotations

from typing import Any, Protocol


class TaskSource(Protocol):
    async def claim_next(self) -> dict[str, Any] | None: ...
    async def ack(self, task_id: str, stream_id: str | None = None) -> None: ...
    async def save_checkpoint(self, task_id: str, checkpoint: dict[str, Any]) -> None: ...
    async def load_checkpoint(self, task_id: str) -> dict[str, Any] | None: ...
    async def clear_checkpoint(self, task_id: str) -> None: ...
    async def list_inflight(self) -> list[str]: ...
    async def close(self) -> None: ...
